language: node_js
node_js:
  - 10

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build:prod
  - env

deploy:
  - provider: pages
    target_branch: gh-pages
    skip_cleanup: true
    keep_history: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/
    on:
      branch: master